# Generated by Django 5.1.7 on 2025-05-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
